version: '3.8'

services:
  fwd-blockchain-node:
    build: .
    container_name: fwd-node
    ports:
      - "8545:8545"
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8545"]
      interval: 10s
      timeout: 5s
      retries: 3
