/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { FWDAnchor, FWDAnchorInterface } from "../../contracts/FWDAnchor";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "root",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RootAnchored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_root",
        type: "bytes32",
      },
    ],
    name: "anchorRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "anchoredRoots",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_root",
        type: "bytes32",
      },
    ],
    name: "isRootAnchored",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50338061003757604051631e4fbdf760e01b81526000600482015260240160405180910390fd5b61004081610046565b50610096565b600080546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b6102cd806100a56000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c80630948a03f14610067578063715018a61461009e5780638da5cb5b146100a8578063c50b037b146100c3578063ce993b8c146100d6578063f2fde38b14610104575b600080fd5b61008961007536600461024e565b600090815260016020526040902054151590565b60405190151581526020015b60405180910390f35b6100a6610117565b005b6000546040516001600160a01b039091168152602001610095565b6100a66100d136600461024e565b61012b565b6100f66100e436600461024e565b60016020526000908152604090205481565b604051908152602001610095565b6100a6610112366004610267565b61018e565b61011f6101d1565b61012960006101fe565b565b6101336101d1565b600081815260016020526040908190204390819055905182917f668b361b0811dae80275595cd06c4984a762dd284f6d7243547411d096eadde29161018391904290918252602082015260400190565b60405180910390a250565b6101966101d1565b6001600160a01b0381166101c557604051631e4fbdf760e01b8152600060048201526024015b60405180910390fd5b6101ce816101fe565b50565b6000546001600160a01b031633146101295760405163118cdaa760e01b81523360048201526024016101bc565b600080546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b60006020828403121561026057600080fd5b5035919050565b60006020828403121561027957600080fd5b81356001600160a01b038116811461029057600080fd5b939250505056fea2646970667358221220a3ec502d0e3be3cb148713c574f752ac4383cd66f3d0bdccb693bf344bdf869164736f6c63430008180033";

type FWDAnchorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FWDAnchorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FWDAnchor__factory extends ContractFactory {
  constructor(...args: FWDAnchorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FWDAnchor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FWDAnchor__factory {
    return super.connect(runner) as FWDAnchor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FWDAnchorInterface {
    return new Interface(_abi) as FWDAnchorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): FWDAnchor {
    return new Contract(address, _abi, runner) as unknown as FWDAnchor;
  }
}
