/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FWDStaking__factory } from "./FWDStaking__factory";
export { FWDToken__factory } from "./FWDToken__factory";
