import hardhat from "hardhat";
const { ethers } = hardhat;
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Starting deployment on FWD Lifechain...");

  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);

  // 1. Deploy FWD Token
  const FWDToken = await ethers.getContractFactory("FWDToken");
  const token = await FWDToken.deploy();
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log("FWDToken deployed to:", tokenAddress);

  // 2. Deploy FWD Staking
  const FWDStaking = await ethers.getContractFactory("FWDStaking");
  const staking = await FWDStaking.deploy(tokenAddress);
  await staking.waitForDeployment();
  const stakingAddress = await staking.getAddress();
  console.log("FWDStaking deployed to:", stakingAddress);

  // 3. Deploy FWD Anchor
  const FWDAnchor = await ethers.getContractFactory("FWDAnchor");
  const anchor = await FWDAnchor.deploy();
  await anchor.waitForDeployment();
  const anchorAddress = await anchor.getAddress();
  console.log("FWDAnchor deployed to:", anchorAddress);

  // Update frontend config
  const configPath = path.join(process.cwd(), "src/lib/contracts/config.ts");
  const configContent = `// Auto-generated by deploy script - DO NOT EDIT
export const FWD_TOKEN_ADDRESS = "${tokenAddress}";
export const FWD_STAKING_ADDRESS = "${stakingAddress}";
export const FWD_ANCHOR_ADDRESS = "${anchorAddress}";
`;
  fs.writeFileSync(configPath, configContent);
  console.log("Frontend config updated at:", configPath);

  // Also update bridge config if exists
  const bridgeEnvPath = path.join(process.cwd(), ".env");
  let envContent = fs.readFileSync(bridgeEnvPath, "utf8");
  
  const updates = [
    { key: "FWD_ANCHOR_ADDRESS", value: anchorAddress },
    { key: "FWD_STAKING_ADDRESS", value: stakingAddress },
    { key: "FWD_TOKEN_ADDRESS", value: tokenAddress },
    { key: "RPC_URL", value: "https://rpc.fwdlife.vn" }
  ];

  updates.forEach(({ key, value }) => {
    const regex = new RegExp(`${key}=.*`, "g");
    if (envContent.match(regex)) {
      envContent = envContent.replace(regex, `${key}=${value}`);
    } else {
      envContent += `\n${key}=${value}`;
    }
  });

  fs.writeFileSync(bridgeEnvPath, envContent);
  console.log(".env updated with contract addresses.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
