import pkg from "hardhat";
const { ethers } = pkg;
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

async function main() {
  console.log("🚀 Deploying FWD Contracts...");

  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with the account:", deployer.address);

  // Deploy FWDToken
  const FWDToken = await ethers.getContractFactory("FWDToken");
  const fwdToken = await FWDToken.deploy();
  await fwdToken.waitForDeployment();
  const fwdTokenAddress = await fwdToken.getAddress();
  console.log("✅ FWDToken deployed to:", fwdTokenAddress);

  // Deploy FWDStaking
  const FWDStaking = await ethers.getContractFactory("FWDStaking");
  const fwdStaking = await FWDStaking.deploy(fwdTokenAddress);
  await fwdStaking.waitForDeployment();
  const fwdStakingAddress = await fwdStaking.getAddress();
  console.log("✅ FWDStaking deployed to:", fwdStakingAddress);

  // Transfer 100M tokens to the staking contract for rewards pool
  const rewardAmount = ethers.parseUnits("100000000", 18);
  await fwdToken.transfer(fwdStakingAddress, rewardAmount);
  console.log("✅ Transferred 100M FWD to Staking contract for rewards");

  // Save the contract addresses to a config file for Next.js to use
  const configContent = `// Auto-generated by deploy script - DO NOT EDIT\nexport const FWD_TOKEN_ADDRESS = "${fwdTokenAddress}";\nexport const FWD_STAKING_ADDRESS = "${fwdStakingAddress}";\n`;
  
  const configDir = path.resolve("src", "lib", "contracts");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
  fs.writeFileSync(path.join(configDir, "config.ts"), configContent);
  console.log("✅ Contract addresses saved to src/lib/contracts/config.ts");

  console.log("\n📋 Summary:");
  console.log("  FWDToken:   ", fwdTokenAddress);
  console.log("  FWDStaking: ", fwdStakingAddress);
  console.log("\n🎉 Deployment complete!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
